-- Migration 0002 — Execution state machine (Phase 5)
-- Target: PostgreSQL 15.
--
-- NOTE: Alembic itself (`pip install alembic`) is not installed in this
-- build sandbox (no network egress — see Phase 1/5 reports), so this is
-- a hand-written SQL migration rather than an Alembic-autogenerated one.
-- It is written to be dropped into an Alembic migration's upgrade()/
-- downgrade() bodies verbatim once Alembic is available; the numbering
-- (0001, 0002, ...) is deliberately Alembic-revision-shaped.
--
-- WHY THIS MIGRATION EXISTS: the Phase 1 executions.status CHECK
-- constraint ('PENDING','DISPATCHED','SUCCEEDED','FAILED') did not
-- distinguish "ownership claimed, no side effect attempted yet" from
-- "dispatched, outcome unknown" from "dispatched, outcome confirmed" —
-- which is exactly the ambiguity that makes crash recovery unsafe (see
-- docs/EXECUTION_STATE_MACHINE.md). This migration is NOT a silent edit
-- of the already-shipped Phase 1 schema.sql; that file is now the
-- CUMULATIVE current-state convenience copy, and this file is the
-- authoritative historical record of the change.

-- ===== UPGRADE =====

ALTER TABLE executions DROP CONSTRAINT IF EXISTS executions_status_check;

ALTER TABLE executions ADD COLUMN IF NOT EXISTS claimed_at TIMESTAMPTZ;
ALTER TABLE executions ADD COLUMN IF NOT EXISTS dispatched_at TIMESTAMPTZ;

-- Best-effort forward-mapping of any pre-existing rows under the old
-- state names, in case this runs against a database that already has
-- Phase 1-era executions rows (not expected pre-launch, but a real
-- migration should not silently corrupt existing data if it exists).
UPDATE executions SET status = 'CLAIMED' WHERE status = 'PENDING';
UPDATE executions SET status = 'VERIFIED_SUCCESS' WHERE status = 'SUCCEEDED';
UPDATE executions SET status = 'DISPATCH_FAILED' WHERE status = 'FAILED';
-- 'DISPATCHED' is a valid name in both old and new schemes; no change needed.

ALTER TABLE executions ADD CONSTRAINT executions_status_check CHECK (status IN (
    'CLAIMED', 'DISPATCHED', 'VERIFIED_SUCCESS', 'VERIFIED_FAILED',
    'DISPATCH_FAILED', 'UNCERTAIN'
));

CREATE INDEX IF NOT EXISTS idx_executions_status ON executions(status);
CREATE INDEX IF NOT EXISTS idx_executions_allocation ON executions(allocation_id);

-- ===== DOWNGRADE =====
-- (kept for completeness; lossy — UNCERTAIN/CLAIMED/VERIFIED_FAILED/
-- DISPATCH_FAILED have no faithful representation in the old 4-state
-- scheme, so this is a best-effort collapse, not a true inverse.)

-- ALTER TABLE executions DROP CONSTRAINT IF EXISTS executions_status_check;
-- UPDATE executions SET status = 'PENDING' WHERE status = 'CLAIMED';
-- UPDATE executions SET status = 'SUCCEEDED' WHERE status = 'VERIFIED_SUCCESS';
-- UPDATE executions SET status = 'FAILED' WHERE status IN ('VERIFIED_FAILED', 'DISPATCH_FAILED', 'UNCERTAIN');
-- ALTER TABLE executions ADD CONSTRAINT executions_status_check CHECK (status IN ('PENDING','DISPATCHED','SUCCEEDED','FAILED'));
-- ALTER TABLE executions DROP COLUMN IF EXISTS claimed_at;
-- ALTER TABLE executions DROP COLUMN IF EXISTS dispatched_at;
-- DROP INDEX IF EXISTS idx_executions_status;
-- DROP INDEX IF EXISTS idx_executions_allocation;
